config/routes.rb
Rails.application.routes.draw do
  root 'basic_pages#home'
  
  get 'basic_pages/home', to: 'basic_pages#home'
  get 'basic_pages/team', to: 'basic_pages#team'
  get 'basic_pages/contact', to: 'basic_pages#contact'
  get 'basic_pages/welcome/:first_name', to: 'basic_pages#welcome'

  resources :gossips
  resources :user
  resources :city
  
  resources :gossips do
    resources :comments
   end

  resources :sessions, only:[:new, :create, :destroy]
  resources :gossips do
    resources :likes
   end
 


  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  validates :zip_code, presence: true, uniqueness: true
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 20}
  validates :content, presence: true
  belongs_to :user, optional: true
  has_many :tags
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: 'User'
  belongs_to :sender, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}
  belongs_to :city, optional: true
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def show
    @city = City.find(params[:id])
    @gossips = []
    Gossip.all.each do |gossip|
      if gossip.user.city_id == params[:id].to_i
        @gossips << gossip
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :create, :update]
  
  def new
    @gossip = Gossip.find(params[:gossip_id]) 
    @comment = Comment.new
  end

  def create
    @gossip = Gossip.find(params[:gossip_id])
    user = User.all.sample
    @comment = Comment.create(content: params[:content], gossip: @gossip, user: user)
    redirect_to gossip_path(@gossip)
  end 

  def edit 
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(content: params[:content])
      redirect_to basic_pages_home_path
    else
      render :edit
    end
  end

  def destroy 
    @comment = Comment.find(params[:id])
    Comment.delete(@comment)
    return redirect_to basic_pages_home_path
  end

  private
  def authenticate_user
    unless current_user
      redirect_to new_session_path
    end
  end

  def comment
    @comment = Comment.find(params[:id])
  end

  def gossip_id
    @gossip = Gossip.find(params[:gossip_id])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :create, :update]
  
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Gossip.find(params[:id]).comments
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(post_params)
    @gossip.update(user: current_user)
 

    redirect_to gossip_path(@gossip.id)
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(post_params)
      redirect_to basic_pages_home_path
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to basic_pages_home_path
  end

  private
  def post_params
    post_params = params.require(:gossip).permit(:title, :content)
  end

  private
  def authenticate_user
    unless current_user
      redirect_to new_session_path
    end
  end

  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @user = current_user.id
    @gossip = params[:gossip_id]
    likes = {user_id: @user, gossip_id: @gossip}
    @like = Like.new(likes)

    @like.save!
    if @like.save
      redirect_to basic_pages_home_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    # cherche s'il existe un utilisateur en base avec l’e-mail
    user = User.find_by(email: params[:email])

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to basic_pages_home_path
    else
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to basic_pages_home_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
    @city = City.all
  end

  def show
    user_id = params[:id]
    @user = User.find(user_id)
  end

  def create
    @city = City.all
    city = City.find(params[:city])
    @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      description: params[:description],
      email: params[:email],
      age: params[:age],
      city: city,
      password: params[:password],
      password_confirmation: params[:password_confirmation])

      if @user.save
        redirect_to basic_pages_home_path
      else
        puts @user.errors.full_messages
        render "new"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/city/show.html.erb
<h1>Les gossips de <%= @city.name %></h1>
<br/>

<!-- list group gossips -->
<div class="container">
<% @gossips.each_with_index do |gossip, index| %>
  <div class="row">
    <div class="col-4">
      <div class="list-group" id="list-tab" role="tablist">
        <a class="list-group-item list-group-item-action" id="list-gossip<%=gossip.id%>-list" data-toggle="list" role="tab" aria-controls="gossip<%=gossip.id%>" href="#list-gossip<%=gossip.id%>">
          <div class="d-flex justify-content-between">
            <h5 class="mb-2">Gossip n°<%=index + 1%></h5>
            <small><%=gossip.created_at%></small>
          </div>
          <p class="mb-2"><%=gossip.title%></p>
          <small>Created by <%=gossip.user.first_name%></small>

          <% if current_user%>
          <%= button_to 'Like', gossip_likes_path(gossip), method: :post, class:"btn btn-outline-info btn-sm" %>
            <p class="p-2"> <%= gossip.likes.count %> <i class="fas fa-heart"></i></p>
          <%end%>

          <a class="btn btn-outline-secondary btn-sm" role="button" href="<%= gossip_path(gossip.id) %>">Voir le détail</a>
        </a>
      </div>
    </div>
    <div class="col-8">
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade" id="list-gossip<%=gossip.id%>" role="tabpanel" aria-labelledby="list-gossip<%=gossip.id%>-list"><%=gossip.content%></div>
      </div>
    </div>
  </div>
  <br/>
<% end %>
</div>

app/views/comments/edit.html.erb
<h1>Modifier le commentaire </h1>

<%= form_for([@gossip,@comment],:url=>gossip_comment_path, :method => :put) do |f| %>
  <%= label_tag 'Commentaire' %>
  <%= text_field_tag 'content', @comment.content %>
  <br> <br>
  <%= submit_tag "Modifier", class: "btn btn-secondary " %>
<% end %>

app/views/gossips/edit.html.erb
<h1>Éditer le gossip</h1>

<%= form_for @gossip do |f| %>

  <div class="form-group">
    <label>Titre du gossip</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Contenu du gossip</label>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <button type="submit">Modifier le gossip</button>
  </div>

<% end %>

app/views/gossips/index.html.erb
<h1>Gossips#index</h1>
<p>Find me in app/views/gossips/index.html.erb</p>

app/views/gossips/new.html.erb
<h1>Créer un gossip</h1>

<%= form_for @gossip do |f| %>

  <div class="form-group">
    <label>Titre du gossip</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Contenu du gossip</label>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= current_user.first_name %>
  </div>

  <div class="form-group">
    <button type="submit">Créer le gossip</button>
  </div>
<% end %>

app/views/gossips/show.html.erb
<h1>Titre : <%= @gossip.title %></h1>
<p>Contenu : <%= @gossip.content %></p>
<p>Auteur : <%= @gossip.user.first_name %> <%= @gossip.user.last_name%></p>
<p>Ville de l'auteur : <%= @gossip.user.city.name %></p>

<a class="btn btn-outline-secondary btn-sm" role="button" href="<%=city_path(@gossip.user.city_id)%>">Voir les gossips de <%=@gossip.user.city.name%></a>

<p>
  <%= link_to "Voir l'auteur", {controller: "user", action: "show", id: @gossip.user.id}, class: "btn btn-primary mt-3" %>
</p>

<% if current_user == @gossip.user.id %>
  <p>
    <a href="<%= edit_gossip_path %>" class="btn btn-primary">Modifier le gossip</a>
  </p>

  <p>
  <%= link_to "Supprimer le gossip", gossip_path(@gossip), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure ?"
  } %>
  </p>
<% end %>


<% if current_user%>
  <%= button_to 'Like', gossip_likes_path(@gossip), method: :post, class:"btn btn-outline-info btn-sm" %>
  <p class="p-2"> <%= @gossip.likes.count %>  <i class="fas fa-heart"></i></p>
<%end%>


<%= form_tag gossip_comments_path(@gossip), action: 'create', method: "post" do %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <%= label_tag 'Lâche ton commentaire' %>
  <%= text_field_tag 'content', @content, placeholder: 'Écris ton commentaire..'%> <br>
  <%= submit_tag "Publie ton commentaire" %>
<% end %>


<% ordered_comment = @comment.order(created_at: :desc) %>
<% ordered_comment.each do |comment| %>
  <div class= "col-4 col-sm-4 col-md-4 col-lg-4 mt-5 text-center" > 
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <p class="card-text">Auteur : <%= comment.user.first_name %></p>
          <p class="card-text">Commentaire : <%= comment.content %></p>
          <%= link_to "Modifier", edit_gossip_comment_path(@gossip, comment), class:"btn btn-primary" %>
         <%= link_to "Supprimer", gossip_comment_path(@gossip, comment.id),data: {turbo_method: :delete,turbo_confirm: "Are you sure ?"} %>
        </div>
      </div>
    </div>
<% end %>




<p>
  <a href="<%= basic_pages_home_path %>" class="btn btn-primary">Revenir aux gossips</a>
</p>

app/views/user/new.html.erb
    <h1 class="h3 mb-3 fw-normal">INSCRIPTION</h1>

    <%= form_tag url_for(action: 'create'), method: 'post' do %>
      <div class="form-group">
        <%= label_tag 'Prénom'%>
        <%= text_field_tag 'first_name', value = nil%>
      </div>

      <div class="form-group">
        <%= label_tag 'Nom'%>
        <%= text_field_tag 'last_name', value = nil%>
      </div>

      <div class="form-group">
        <%= label_tag 'Email'%>
        <%= text_field_tag 'email', value = nil%>
      </div>

      <label for="cities"> Choose a city :</label>
      <form id="cityform">
      <select id="cities" name="city"> 
        <% @city.each do |city| %>
          <option value="<%= city.id %>"><%= city.name %></option>
        <% end %>                 
      </select>

      <div class="form-group">
        <%= label_tag 'Mot de passe'%>
        <%= password_field_tag 'password', value = nil%>
      </div>
    
      <div class="form-group">
        <%= label_tag 'Confirmation'%>
        <%= password_field_tag 'password_confirmation', value = nil%>
      </div>

      <div class="form-group">
        <p><%= check_box_tag 'remember_me' %> Se souvenir de moi </p>
      </div>

      <%= submit_tag "Submit", class: "btn btn-lg btn-primary" %>

      <%= link_to "Déjà inscrit(e) ?", new_session_path %>
   <% end %>

app/views/user/show.html.erb
<h1>Prénom : <%= @user.first_name %> <%= @user.last_name %></h1>
<p>Nom : <%= @user.description %></p>
<p>Email : <%= @user.email %></p>
<p>Âge : <%= @user.age %></p>
<p>Ville : <%= @user.city.name%></p>

<a class="btn btn-outline-secondary btn-sm" role="button" href="<%=city_path(@user.city_id)%>">Voir les gossips de <%=@user.city.name%></a>