config/routes.rb
Rails.application.routes.draw do
  root 'basic_pages#home'
  
  get 'basic_pages/home', to: 'basic_pages#home'
  get 'basic_pages/team', to: 'basic_pages#team'
  get 'basic_pages/contact', to: 'basic_pages#contact'
  get 'basic_pages/welcome/:first_name', to: 'basic_pages#welcome'

  resources :gossips
  resources :user
  resources :city
  
  resources :gossips do
    resources :comments
   end

  resources :sessions, only:[:new, :create, :destroy]
  resources :gossips do
    resources :likes
   end
 


  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  validates :zip_code, presence: true, uniqueness: true
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 20}
  validates :content, presence: true
  belongs_to :user, optional: true
  has_many :tags
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: 'User'
  belongs_to :sender, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}
  belongs_to :city, optional: true
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
end

app/controllers/basic_pages_controller.rb
class BasicPagesController < ApplicationController
  def home
    @gossips = Gossip.all
  end

  def team
  end

  def contact
  end

  def welcome
    @first_name = params[:first_name]
  end
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def show
    @city = City.find(params[:id])
    @gossips = []
    Gossip.all.each do |gossip|
      if gossip.user.city_id == params[:id].to_i
        @gossips << gossip
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :create, :update]
  
  def new
    @gossip = Gossip.find(params[:gossip_id]) 
    @comment = Comment.new
  end

  def create
    @gossip = Gossip.find(params[:gossip_id])
    user = User.all.sample
    @comment = Comment.create(content: params[:content], gossip: @gossip, user: user)
    redirect_to gossip_path(@gossip)
  end 

  def edit 
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(content: params[:content])
      redirect_to basic_pages_home_path
    else
      render :edit
    end
  end

  def destroy 
    @comment = Comment.find(params[:id])
    Comment.delete(@comment)
    return redirect_to basic_pages_home_path
  end

  private
  def authenticate_user
    unless current_user
      redirect_to new_session_path
    end
  end

  def comment
    @comment = Comment.find(params[:id])
  end

  def gossip_id
    @gossip = Gossip.find(params[:gossip_id])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :create, :update]
  
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Gossip.find(params[:id]).comments
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(post_params)
    @gossip.update(user: current_user)
 

    redirect_to gossip_path(@gossip.id)
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(post_params)
      redirect_to basic_pages_home_path
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to basic_pages_home_path
  end

  private
  def post_params
    post_params = params.require(:gossip).permit(:title, :content)
  end

  private
  def authenticate_user
    unless current_user
      redirect_to new_session_path
    end
  end

  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @user = current_user.id
    @gossip = params[:gossip_id]
    likes = {user_id: @user, gossip_id: @gossip}
    @like = Like.new(likes)

    @like.save!
    if @like.save
      redirect_to basic_pages_home_path
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
    @city = City.all
  end

  def show
    user_id = params[:id]
    @user = User.find(user_id)
  end

  def create
    @city = City.all
    city = City.find(params[:city])
    @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      description: params[:description],
      email: params[:email],
      age: params[:age],
      city: city,
      password: params[:password],
      password_confirmation: params[:password_confirmation])

      if @user.save
        redirect_to basic_pages_home_path
      else
        puts @user.errors.full_messages
        render "new"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/basic_pages/contact.html.erb
<body>
<section class="contact-us">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="section-title">
                    <h2>Nous contacter</h2>
                    <p>Vous pouvez nous envoyer toutes vos demandes via le formulaire ci-dessous !</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-7">
                <form action="/" class="mb-4 mb-lg-0">
                    <div class="form-row">
                        <div class="col-md-6 form-group">
                            <input type="text" name="name" class="form-control" id="name" placeholder="Nom" />
                        </div>
                        <div class="col-md-6 form-group">
                            <input type="email" class="form-control" name="email" id="email" placeholder="Email" />
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Sujet" />
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="message" placeholder="Écrivez votre message ici"></textarea>
                    </div>
                    <button type="submit" class="btn btn-light">Envoyer</button>
                </form>
            </div>

            <div class="col-lg-5">
                <div class="map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3571289.733943155!2d76.08560099999998!3d29.058775699999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390e4a4b98404f57%3A0x75ffae70833e8448!2sShahbad%2C%20Haryana%20136135!5e0!3m2!1sen!2sin!4v1594195370933!5m2!1sen!2sin" width="100%" height="350" frameborder="0" style="border: 0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
            </div>
        </div>
    </div>
</section>
</body>

app/views/basic_pages/home.html.erb
<html>
  <body>
  <!-- Jumbotron -->
<div class="p-5 text-center bg-image rounded-3" style="background: #af8070; height: 300px;">
  <div>
    <div class="d-flex justify-content-center align-items-center h-100">
      <div class="text-white">
        <h1 class="mb-3">THE GOSSIP PROJECT</h1>

       <% if session[:current_user] %>
        <h4 class="mb-3">Bienvenue <%= User.find_by(id: session[:user_id]).first_name %>, te voici sur notre super site de potins !</h4> <br>
      <% else %>
          <h4 class="mb-3">Bienvenue, te voici sur notre super site de potins !</h4> <br>
      <% end %>
        <a href="<%= new_gossip_path %>" class="btn">Créer un gossip</a>
      </div>
      
    </div>
  </div>
</div> <br>
<!-- Jumbotron -->

<div class="container-fluid">
<h2>Voici la liste de tous les gossips :</h2>
<div class="row">
  <% @ordered_gossips = @gossips.order(:id) %>
  <% @ordered_gossips.each do |gossip| %>
    <div class= "col-4 col-sm-4 col-md-4 col-lg-4 mt-5 text-center" > 
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= gossip.id %> . <%= gossip.title %></h5>
          <p class="card-text">Auteur : <%= gossip.user.first_name %></p>
          <p class="p-2 text-right"> Commentaires : <%= gossip.comments.count %> <i class="fas fa-heart"></i></p>

          <% if current_user %>
          <%= button_to 'Like', gossip_likes_path(gossip), method: :post, class:"btn btn-outline-info btn-sm float-right ml-2" %>
          <p class="p-2 text-right"> <%= gossip.likes.count %> <i class="fas fa-heart"></i></p>
          <% end %>

          <a href="<%= gossip_path(gossip.id)%>" class="btn">Voir le gossip</a>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>
  <body>
</html>

app/views/basic_pages/team.html.erb
<div class="py-5 team4">
  <div class="container">
    <div class="row justify-content-center mb-4">
      <div class="col-md-7 text-center">
        <h3 class="mb-3">Notre SUPER team</h3>
        <h6 class="subtitle">On vous présente notre team : la meilleure que vous pourrez trouver (et c'est pas une blague)</h6>
      </div>
    </div> <br><br>
    <div class="row">
     <!-- column  -->
      <div class="col-lg-3 mb-4">
        <!-- Row -->
        <div class="row">
          <div class="col-md-12">
            <img src="https://cdn.discordapp.com/attachments/1194577646160453704/1207048298888826931/IMG_8610.png?ex=65de3a54&is=65cbc554&hm=ebeca88623ec128563172a5c05a87a42a573d4ccc104d341c09c650b112e8595&" alt="wrapkit" class="img-fluid rounded-circle" />
          </div>
          <div class="col-md-12 text-center">
            <div class="pt-2">
              <h5 class="mt-4 font-weight-medium mb-0">Nicolas</h5>
              <h6 class="subtitle mb-3">Property Specialist</h6>
              <p>You can relay on our amazing features list and also our customer services will be great experience.</p>
              <ul class="list-inline">
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-behance"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Row -->
      </div>
      <!-- column  -->
      <!-- column  -->
      <div class="col-lg-3 mb-4">
        <!-- Row -->
        <div class="row">
          <div class="col-md-12">
            <img src="https://scontent-mrs2-2.xx.fbcdn.net/v/t39.30808-6/320683862_2061867920688838_1582574588396846473_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=9c7eae&_nc_ohc=ReRlDfnd12QAX98VtTg&_nc_ht=scontent-mrs2-2.xx&oh=00_AfBWCJADq_NqEM4Ed6I380HTdLhxH09KKwrH4vtMlUwYpw&oe=65D0C6A7" alt="wrapkit" class="img-fluid rounded-circle" />
          </div>
          <div class="col-md-12 text-center">
            <div class="pt-2">
              <h5 class="mt-4 font-weight-medium mb-0">Anelise</h5>
              <h6 class="subtitle mb-3">Property Specialist</h6>
              <p>You can relay on our amazing features list and also our customer services will be great experience.</p>
              <ul class="list-inline">
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-behance"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Row -->
      </div>
    </div>
  </div>
</div>

app/views/basic_pages/welcome.html.erb
<h1> BONJOUR <%= @first_name %></h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>