config/routes.rb
Rails.application.routes.draw do
  root 'basic_pages#home'
  
  get 'basic_pages/home', to: 'basic_pages#home'
  get 'basic_pages/team', to: 'basic_pages#team'
  get 'basic_pages/contact', to: 'basic_pages#contact'
  get 'basic_pages/welcome/:first_name', to: 'basic_pages#welcome'

  resources :gossips
  resources :user
  resources :city
  
  resources :gossips do
    resources :comments
   end

  resources :sessions, only:[:new, :create, :destroy]
  resources :gossips do
    resources :likes
   end
 


  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  validates :zip_code, presence: true, uniqueness: true
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 20}
  validates :content, presence: true
  belongs_to :user, optional: true
  has_many :tags
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: 'User'
  belongs_to :sender, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}
  belongs_to :city, optional: true
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def show
    @city = City.find(params[:id])
    @gossips = []
    Gossip.all.each do |gossip|
      if gossip.user.city_id == params[:id].to_i
        @gossips << gossip
      end
    end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :create, :update]
  
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Gossip.find(params[:id]).comments
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(post_params)
    @gossip.update(user: current_user)
 

    redirect_to gossip_path(@gossip.id)
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(post_params)
      redirect_to basic_pages_home_path
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to basic_pages_home_path
  end

  private
  def post_params
    post_params = params.require(:gossip).permit(:title, :content)
  end

  private
  def authenticate_user
    unless current_user
      redirect_to new_session_path
    end
  end

  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @user = current_user.id
    @gossip = params[:gossip_id]
    likes = {user_id: @user, gossip_id: @gossip}
    @like = Like.new(likes)

    @like.save!
    if @like.save
      redirect_to basic_pages_home_path
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
    @city = City.all
  end

  def show
    user_id = params[:id]
    @user = User.find(user_id)
  end

  def create
    @city = City.all
    city = City.find(params[:city])
    @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      description: params[:description],
      email: params[:email],
      age: params[:age],
      city: city,
      password: params[:password],
      password_confirmation: params[:password_confirmation])

      if @user.save
        redirect_to basic_pages_home_path
      else
        puts @user.errors.full_messages
        render "new"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title> TheGossipProject </title>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" <%= link_to "Home", basic_pages_home_path %><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Team", basic_pages_team_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Contact", basic_pages_contact_path %></a>
      </li>
    </ul>
    
      <a class="nav-item">
        <% if session[:user_id] %>
          <a class="nav-item"><%= button_to "Log out", session_path(session.id), :method=>:delete, :class=>:destroy, class: "nav-link btn btn-outline-secondary" %></a>
        <% elsif %>
          <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Bouton de connexion
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item"><%= link_to "Sign in", new_session_path %></a>
              <a class="dropdown-item"><%= link_to "Sign up", new_user_path %></a>
            </div>
          </div>
        <% end %>
      </a>
  </div>
</nav>
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>